# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='travel_radius',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
