# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20170117_0218'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='imagerprofile',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='imagerprofile',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='travel_radius',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
    ]
