# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0003_auto_20170119_0345'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='imagerprofile',
            managers=[
            ],
        ),
    ]
