# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0005_auto_20170202_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='bio',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='camera_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='personal_website',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='photo_type',
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
    ]
