# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0002_auto_20170125_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='phototographer',
            new_name='photographer',
        ),
    ]
