# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_auto_20170125_0115'),
        ('imager_images', '0002_auto_20170124_1507'),
    ]

    operations = [
    ]
