# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0004_merge_20170125_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='/media/'),
        ),
    ]
